Resources:
  ProjectVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '192.168.10.0/24' 
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Sai
          Value: ProjectVpc

  PublicSubnet1A:
    Type:  'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref ProjectVpc
      CidrBlock: '172.16.1.0/24'  # Unique CIDR block
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true 
      Tags:
        - Key: Sai
          Value: PublicSubnet1A

  AppPrivateSubnet1A:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref ProjectVpc
      CidrBlock: '172.16.2.0/24'  # Unique CIDR block
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Sai
          Value: AppPrivateSubnet1A

  DataPrivateSubnet1A:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: '!RefcProjectVpc' 
      CidrBlock: '172.16.3.0/24'  # Unique CIDR block
      AvailabilityZone: '!Select [0, !GetAZs '']'
      Tags:
        - Key: Sai
          Value: DataPrivateSubnet1A

  PublicSubnet2B:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: '!Ref ProjectVpc'
      CidrBlock: '172.16.4.0/24'  # Unique CIDR block
      AvailabilityZone: '!Select [1, !GetAZs '']'
      MapPublicIpOnLaunch: true  
      Tags:
        - Key: Sai
          Value: PublicSubnet2B

  AppPrivateSubnet2B:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: '!Ref ProjectVpc'
      CidrBlock: '172.16.5.0/24'  # Unique CIDR block
      AvailabilityZone: '!Select [1, !GetAZs '']'
      Tags:
        - Key: Sai
          Value: AppPrivateSubnet2B

  DataPrivateSubnet2B:
    Type: 'AWS::EC2::Subnet' 
    Properties:
      VpcId: '!Ref ProjectVpc'
      CidrBlock: '172.16.6.0/24'  # Unique CIDR block
      AvailabilityZone: '!Select [1, !GetAZs '']'
      Tags:
        - Key: Sai
          Value: DataPrivateSubnet2B