Resources:
  ProjectVpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "192.168.10.0/24"
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Sai
          Value: ProjectVpc

  PublicSubnet1A:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ProjectVpc
      CidrBlock: "192.168.10.0/28" # Unique CIDR block
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Sai
          Value: PublicSubnet1A

  AppPrivateSubnet1A:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ProjectVpc
      CidrBlock: "192.168.10.16/28" # Unique CIDR block
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Sai
          Value: AppPrivateSubnet1A

  DataPrivateSubnet1A:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ProjectVpc
      CidrBlock: "192.168.10.32/28" # Unique CIDR block
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Sai
          Value: DataPrivateSubnet1A

  PublicSubnet2B:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ProjectVpc
      CidrBlock: "192.168.10.48/28" # Unique CIDR block
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Sai
          Value: PublicSubnet2B

  AppPrivateSubnet2B:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ProjectVpc
      CidrBlock: "192.168.10.64/28" # Unique CIDR block
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Sai
          Value: AppPrivateSubnet2B

  DataPrivateSubnet2B:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ProjectVpc
      CidrBlock: "192.168.10.80/28" # Unique CIDR block
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Sai
          Value: DataPrivateSubnet2B
